### ISSUE TITLE
errors with uneven pulse dimensions

### ISSUE THREAD

**Issue by moellep** [radiasoft/rslaser#15]
Running simulations with a LaserPulse with nx_slice != ny_slice will cause problems when you try to extract the intensity. I think the mesh is ny * nx, so the reshapes should have ny as the first parameter to np.zeros() or np.reshape().

As a test case, try changing the pulse params in the new multiple_crystal_passes notebook example:
```python
params = PKDict(
    # ...
    nx_slice    = pulse_ncells,
    ny_slice    = pulse_ncells + 10,
)
```

This will cause an error when it tries to plot the total 2d elec field.
plt.pcolormesh(lp_wfr_x*(1e3), lp_wfr_y*(1e3), intens_2d_init, cmap=plt.cm.viridis, shading='auto')
```TypeError: Dimensions of C (256, 266) are incompatible with X (256) and/or Y (266); see help(pcolormesh)```

Swapping the nx and ny parameters in pulse.extract_total_2d_elec_fields() and extract_total_2d_phase() seems to fix the problem.

There may be other assumptions that nx_slice == ny_slice, so it might be easier to remove the two parameters and replace with one value which gets used for both.

**Comment by bruhwiler** [comment]
I agree with the suggestion that we require nx_slice == ny_slice within rslaser

**Comment by k-wolfinger** [comment]
This is being addressed in issue https://github.com/radiasoft/rslaser/issues/49 with branch https://github.com/radiasoft/rslaser/tree/49-odd-n-cells-lct

**Comment by k-wolfinger** [comment]
This has been addressed with PR https://github.com/radiasoft/rslaser/pull/50
