### ISSUE TITLE
simulate multi-crystal amplifier with BELLA Center parameters

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/rslaser#22]

**Comment by bruhwiler** [comment]
Data from LBNL is required; however, you could set up a 4-crystal configuration, with 3 passes per crystal and reasonable mirror locations to get started.

**Comment by k-wolfinger** [comment]
This is being addressed with a notebook in https://github.com/radiasoft/rslaser-examples/issues/3. Any necessary changes to the code will be handled with a branch here, if/when they come up.

**Comment by k-wolfinger** [comment]
Closing this, as the related notebook has been completed for now: https://github.com/radiasoft/rslaser-examples/blob/main/laser_propagation/amplifier_100TW_Bella.ipynb
