### ISSUE TITLE
Fix LCT oversampling

### ISSUE THREAD

**Issue by bnash** [radiasoft/rslaser#47]
For short propagation lengths with a drift or Gaussian duct matrix, the LCT should increase the number of sample points or range by very little. The current implementation does not meet these criteria.

**Comment by bnash** [comment]
An initial observation is that the sampling will increase depending on the value of l_scale.
For a Gaussian beam, in order to transform into a square in normalized coordinates in Wigner space, one should set l_scale = sqrt(π) w_0, with w_0 the beam width at the waist.
We need to do more studies, but this choice for l_scale may resolve the issue.

**Comment by bruhwiler** [comment]
The guidance provided here is working well.
It would be nice if the mesh didn't grow at all, but that is not a priority.

I've reduced the priority of this issue from 1 to 2.
We should consider closing this issue.

**Comment by bnash** [comment]
A point to note, in discussion with @dtabell, is that if we are to automate the calcuation of l_scale, using the above prescription, it should belong to the pulse object, and not the crystal object.

**Comment by bnash** [comment]
Another observation: resampling in LCT should preserve the parity of the number of points, so that we don't run afoul of the restriction that N needs to be even (relating to different conventions between SRW and LCT definitions of abscissae).

**Comment by bruhwiler** [comment]
Stop work on this issue.
