### ISSUE TITLE
Create a dedicated class for laser heating

### ISSUE THREAD

**Issue by morhenderson** [radiasoft/rslaser#48]
Create a class that encapsulates & parameterizes laser heating calculations for the Crystal element. An instance of this class should be initialized by a Crystal to compute/load its n0/n2 values & ABCD matrix. The new class should feature:
- Options for both steady-state (time-independent) & transient (time-dependent, load on/off) behavior
- Parameterized material properties (alpha, density, thermal conductivity, & specific heat capacity)
- A selection of heat load expressions & the option to use a FEniCS UserExpression
- Generalized evaluation points in cylindrical coordinates (incl. cylindrical grid interpolation)
- Wavelength & temperature dependence for index of refraction
- Robust model storage/retrieval methods to limit expensive simulation calls
- 2D & 3D plotting methods for thermal/thermo-optic results

**Comment by bruhwiler** [comment]
@morhenderson -- please provide an estimate for when this effort will be completed.
It would be great if you could wrap it up this week.

**Comment by bruhwiler** [comment]
It would be a good idea to discuss with @bnash and show him the new code, because he needs to think about consistency between the thermal and amplifier tabs in the Silas app.

**Comment by morhenderson** [comment]
The code for the new class is all written and ready for testing, though I haven't discussed with software how it will work with the app.

I'm happy to meet with @bnash sometime this week to go over it and can get started on testing to make sure I'm not breaking anything in the examples or notebooks. There are one or two other things I'd like to discuss with @k-wolfinger as well before this goes into any kind of production.

**Comment by bruhwiler** [comment]
Discussions regarding the Silas app are not part of the scope and should not delay creation of a PR.
When the PR is reviewed, we need to document any changes that break the API and notify the Sirepo team.

**Comment by morhenderson** [comment]
Sorry, I'm realizing I never gave an actual estimate. I plan to have testing done and a PR created today or tomorrow.

The comment about the app was more about my ability to assist @bnash with consistency between tabs. I met with @k-wolfinger about this and kept it in mind when designing the new class, but it will likely need some further consideration.
