### ISSUE TITLE
implement a flat ideal mirror for 180 degree reflection

### ISSUE THREAD

**Issue by k-wolfinger** [radiasoft/rslaser#5]
Simplest implementation would be a flag in the LaserPulse class indicating whether the pulse is traveling 'forward' or 'backward'.  A 180 degree reflection from a flat ideal mirror would simply toggle the flag.

We will need to consider other reflection angles in the future. For a flat ideal mirror, in this more general case, the boolean flag could be replaced with an angle that defines the direction. In this case, encountering a mirror with a specified angle would simply require an appropriate update of the internal angle variable.

SRW has a flat mirror object, but previous experience indicates that it only works reliably for grazing incidence angles, which is the case for X-ray optics.

**Comment by bnash** [comment]
Or, I guess you could define the new coordinates in such a way that this reflection doesn't happen. Then you need to be particularly careful when it passes through the crystal again.

**Comment by bruhwiler** [comment]
Thanks @bnash -- I believe it would be best to flip the electric fields correctly when the mirror element is encountered.

**Comment by k-wolfinger** [comment]
For the mirror issue, I have:
- Added a pulse_direction param to the LaserPulse
- Added the function LaserPulse.ideal_mirror_180(): In this function the pulse direction is changed by 180 degrees (from 0 to 180 or from 180 to 0). For each laser slice, the fields are extracted from the wfr, flipped, and used to make a new wfr
- When propagating through a crystal, checked this pulse_direction param to set the iteration order through the crystal slices
