### ISSUE TITLE
apply the 'variable n2 propagator' to more recent experimental data

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/rslaser#8]
Please put the relevant WFS data files into ..../rslaser/rslaser/package_data/
Include data received yesterday from LBNL.

The naming convention used for the data files already in that directory is confusing.
I suggest coming up with a better file naming convention.

**Comment by k-wolfinger** [comment]
Since the intensity/phase data are different sizes, I'm going to make a function in pulse.py which cuts the larger array to the size of the other (or 64, whichever is larger).

This will allow me to apply the variable n2 propagator for now. We can take it out later if we want.

**Comment by bruhwiler** [comment]
Data has been received from LBL -- thermal lensing without laser gain

**Comment by k-wolfinger** [comment]
Data will be added here, but the notebook will be completed with https://github.com/radiasoft/rslaser-examples/issues/4
