### ISSUE TITLE
test single-pass propagation at higher resolution

### ISSUE THREAD

**Issue by k-wolfinger** [radiasoft/rslaser#9]
Instead of using the WFS data files, create an ideal Gaussian laser pulse at a waist (flat phase profile).
Consider n2 that is radially varying and also radially invariant.
Explore the behavior as the mesh resolution is increased from 64x64 towards 1028x1028

**Comment by k-wolfinger** [comment]
[Function initialization with n2 variation.pdf](https://github.com/radiasoft/rslaser/files/11174352/Function.initialization.with.n2.variation.pdf)

**Comment by k-wolfinger** [comment]
[Function initialization and n2 variation.pdf](https://github.com/radiasoft/rslaser/files/11174815/Function.initialization.and.n2.variation.pdf)

**Comment by bruhwiler** [comment]
The problem has been resolved with a 2D switching function, so this no longer needs to be pursued.
